In [ ]:
import numpy as np

#Array Creations

In [ ]:
# 1D
arr1 = np.array([1,2,3])
arr1.ndim
arr1.shape
arr1.dtype

# 2D
arr2 = np.array([[1,2,3],[3,2,1]])
arr2.ndim
arr2.shape

# 3D
arr3 = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
arr3.ndim
arr3.shape

(2, 2, 3)

#Boolean Indexing

In [ ]:
# Boolean Indexing
arr = np.array([[1,2,3,4],[5,6,7,8]])

# for boolean
arr %2 == 1

# for values
arr[arr %2 == 1]

# multiple conditions boolean
(arr == 1) | (arr == 2)

# multiple conditions values
arr[(arr == 1) | (arr == 2)]

# assigning values
arr[(arr == 1) | (arr == 2)] = 9,10
arr

array([[ 9, 10,  3,  4],
       [ 5,  6,  7,  8]])

#Problems 1

1.Create a random integer array in between 1 to 10000 of shape (10,5) and filter odd numbers from the array.

In [ ]:
arr = np.random.randint(1,10001,(10,5)).astype(float)
arr

array([[2815., 7157., 3843., 7299.,  271.],
       [1374.,   38., 1611., 5286., 5842.],
       [4123., 3820.,   43., 8961., 8303.],
       [2622., 2004., 9240., 3350., 1950.],
       [7291., 4467., 4238., 5018., 2909.],
       [8595., 8490., 9514., 7748., 6992.],
       [4439., 9478., 7889., 9826., 6421.],
       [2346.,  762., 6076., 9527., 4774.],
       [7680., 3254., 2014., 7567., 3875.],
       [9081., 4097., 8570., 6330., 5494.]])

2.Compute the mean, median and standard deviation of above array Row-wise and column-wise.

In [ ]:
# column
print("Column")
print("Mean:",np.mean(arr,axis=0))
print("Median:",np.median(arr,axis=0))
print("Standard Devation:",np.std(arr,axis=0))

print()

# row
print("Row")
print("Mean:",np.mean(arr,axis=1))
print("Median:",np.median(arr,axis=1))
print("Standard Devation:",np.std(arr,axis=1))

Column
Mean: [5036.6 4356.7 5303.8 7091.2 4683.1]
Median: [4281.  3958.5 5157.  7433.  5134. ]
Standard Devation: [2714.7895388  2997.42226088 3264.54449503 1993.5462272  2328.10611657]

Row
Mean: [4277.  2830.2 5050.  3833.2 4784.6 8267.8 7610.6 4697.  4878.  6714.4]
Median: [3843. 1611. 4123. 2622. 4467. 8490. 7889. 4774. 3875. 6330.]
Standard Devation: [2675.84453958 2302.4005212  3265.58441937 2750.5050009  1432.06376953
  849.3885801  1997.34229415 3041.31208527 2320.6811931  1872.53673929]


3.Extract the second and third rows and first and second columns from the above created random matrix.

In [ ]:
print("First and Second Row:")
print(arr[:2])

print()

print("First and Second Column:")
print(arr[:,:2])

First and Second Row:
[[2815. 7157. 3843. 7299.  271.]
 [1374.   38. 1611. 5286. 5842.]]

First and Second Column:
[[2815. 7157.]
 [1374.   38.]
 [4123. 3820.]
 [2622. 2004.]
 [7291. 4467.]
 [8595. 8490.]
 [4439. 9478.]
 [2346.  762.]
 [7680. 3254.]
 [9081. 4097.]]


4.Change all the 3 digit numbers from the random integer matrix with its square root value.

In [ ]:
arr[(arr>99) & (arr<1000)] **= 1/2
arr

array([[2815.        , 7157.        , 3843.        , 7299.        ,
          16.46207763],
       [1374.        ,   38.        , 1611.        , 5286.        ,
        5842.        ],
       [4123.        , 3820.        ,   43.        , 8961.        ,
        8303.        ],
       [2622.        , 2004.        , 9240.        , 3350.        ,
        1950.        ],
       [7291.        , 4467.        , 4238.        , 5018.        ,
        2909.        ],
       [8595.        , 8490.        , 9514.        , 7748.        ,
        6992.        ],
       [4439.        , 9478.        , 7889.        , 9826.        ,
        6421.        ],
       [2346.        ,   27.60434748, 6076.        , 9527.        ,
        4774.        ],
       [7680.        , 3254.        , 2014.        , 7567.        ,
        3875.        ],
       [9081.        , 4097.        , 8570.        , 6330.        ,
        5494.        ]])

5.Find out the index value of maximum number.(row-wise and column-wise).

In [ ]:
print("Row")
print(np.argmax(arr,axis=1))

print()

print("Column")
print(np.argmax(arr,axis=0))


Row
[3 4 3 2 0 2 3 3 0 0]

Column
[9 6 5 6 2]


#NAN (Note A Number)

In [ ]:
# Nan creation
arr[[0,0,-1,-1],[0,-1,0,-1]] = np.nan
arr

array([[nan,  2.,  3., nan],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.],
       [25., 26., 27., 28.],
       [29., 30., 31., 32.],
       [33., 34., 35., 36.],
       [37., 38., 39., 40.],
       [41., 42., 43., 44.],
       [45., 46., 47., 48.],
       [49., 50., 51., 45.],
       [53., 54., 55., 45.],
       [57., 58., 59., 45.],
       [61., 62., 63., 45.],
       [65., 66., 67., 45.],
       [69., 70., 71., 45.],
       [73., 74., 75., 45.],
       [77., 78., 79., 45.],
       [81., 82., 83., 45.],
       [85., 86., 87., 45.],
       [89., 90., 91., 45.],
       [45., 45., 45., 45.],
       [nan, 98., 99., nan]])

In [ ]:
# Nan check
print(np.isnan(arr))
print()

# Nan Count
print(np.isnan(arr).sum())
print()

# Mean without Nan
print(np.nanmean(arr))

[[ True False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [ True False False False  True]]

4

5354.752268423558


In [ ]:
# Nan Replacement
arr[np.isnan(arr)] = np.nanmean(arr)
print(arr)

print()

# Nan Replacement with Indexing
arr[[0,0,-1,-1],[0,-1,0,-1]] = np.nanmean(arr)
print(arr)

[[45.34375  2.       3.      45.34375]
 [ 5.       6.       7.       8.     ]
 [ 9.      10.      11.      12.     ]
 [13.      14.      15.      16.     ]
 [17.      18.      19.      20.     ]
 [21.      22.      23.      24.     ]
 [25.      26.      27.      28.     ]
 [29.      30.      31.      32.     ]
 [33.      34.      35.      36.     ]
 [37.      38.      39.      40.     ]
 [41.      42.      43.      44.     ]
 [45.      46.      47.      48.     ]
 [49.      50.      51.      45.     ]
 [53.      54.      55.      45.     ]
 [57.      58.      59.      45.     ]
 [61.      62.      63.      45.     ]
 [65.      66.      67.      45.     ]
 [69.      70.      71.      45.     ]
 [73.      74.      75.      45.     ]
 [77.      78.      79.      45.     ]
 [81.      82.      83.      45.     ]
 [85.      86.      87.      45.     ]
 [89.      90.      91.      45.     ]
 [45.      45.      45.      45.     ]
 [45.34375 98.      99.      45.34375]]



#Problems 2

1.Create an array from the range of value 1 and 100(included).

In [ ]:
arr = np.arange(1,101).astype(float)
arr

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

2.reshape the above array into shape (25,4).

In [ ]:
arr = arr.reshape(25,4)
arr

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

3.Convert all the value in the 23rd row into nan.

In [ ]:
arr[23] = np.nan
arr

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ nan,  nan,  nan,  nan],
       [ 97.,  98.,  99., 100.]])

4.Convert all numbers above 50 in the 4th column to nan.

In [ ]:
arr[:,3][arr[:,3]>50] = np.nan
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.],
       [25., 26., 27., 28.],
       [29., 30., 31., 32.],
       [33., 34., 35., 36.],
       [37., 38., 39., 40.],
       [41., 42., 43., 44.],
       [45., 46., 47., 48.],
       [49., 50., 51., nan],
       [53., 54., 55., nan],
       [57., 58., 59., nan],
       [61., 62., 63., nan],
       [65., 66., 67., nan],
       [69., 70., 71., nan],
       [73., 74., 75., nan],
       [77., 78., 79., nan],
       [81., 82., 83., nan],
       [85., 86., 87., nan],
       [89., 90., 91., nan],
       [nan, nan, nan, nan],
       [97., 98., 99., nan]])

5.Find out the number of missing values column-wise.

In [ ]:
np.sum(np.isnan(arr),axis=0)

array([ 1,  1,  1, 13])

#Matrix Multiplication

In [ ]:
# Matrix Creation
A = np.random.randint(1,10,(5,3))
B = np.random.randint(1,10,(3,5))
print("A",A,sep="\n")
print()
print("B",B,sep="\n")
print()

# Matrix Multiplication
print("A x B",A.dot(B),sep="\n")
print()
print("B x A",B.dot(A),sep="\n")

A
[[5 9 2]
 [7 3 6]
 [5 8 8]
 [2 6 6]
 [2 2 8]]

B
[[3 3 8 9 2]
 [8 8 4 4 1]
 [3 6 6 4 1]]

A x B
[[ 93  99  88  89  21]
 [ 63  81 104  99  23]
 [103 127 120 109  26]
 [ 72  90  76  66  16]
 [ 46  70  72  58  14]]

B x A
[[ 98 158 158]
 [126 154 128]
 [ 97 119 122]]


In [ ]:
# A's column size should be equal to B's row size.
A = np.random.randint(1,10,(5,3))
B = np.random.randint(1,10,(3,2))

A.dot(B)
# or
np.matmul(A,B)

array([[27, 45],
       [71, 86],
       [80, 69],
       [83, 94],
       [29, 72]])

#Problems 3

Create Arrays

In [ ]:
arr1 = np.array([4, 7, 1, 8, 2, 6])

arr2 = np.array([[1, 3, 5], [2, 4, 6], [3, 6, 9]])

1.Find the shape, size, and datatype of both arrays.

In [ ]:
# Array 1
print("Array1")
print("Shape:",np.shape(arr1))
print("Size:",np.size(arr1))
print("Datatype:",arr1.dtype)

print()

# Array 2
print("Array2")
print("Shape:",np.shape(arr2))
print("Size:",np.size(arr2))
print("Datatype:",arr2.dtype)

Array1
Shape: (6,)
Size: 6
Datatype: int64

Array2
Shape: (3, 3)
Size: 9
Datatype: int64


2.Reshape Array 1 into a 2x3 array and print it.


In [ ]:
arr1 = arr1.reshape(2,3)
print("Array1")
print(arr1)

Array1
[[4 7 1]
 [8 2 6]]


3.Find Sum, Product & Dot product of Array 1 & 2

In [ ]:
arr1_ex = arr1.reshape(2,3)
arr2_ex = arr2[:2]

# Add arr1 and arr2 (after reshaping arr1 to match arr2).
print("Addition:")
print(arr1_ex + arr2_ex)
print()

# Compute the element-wise product of arr1 and arr2.
print("Multiplication:")
print(arr1_ex * arr2_ex)
print()

# Calculate the dot product between arr1 and arr2.
print("Dot Product:")
print(np.dot(arr1,arr2))
print()

Addition:
[[ 5 10  6]
 [10  6 12]]

Multiplication:
[[ 4 21  5]
 [16  8 36]]

Dot Product:
[[ 21  46  71]
 [ 30  68 106]]



#Mean, Median, Std, Sum

4.Find the mean, median, and standard deviation of both arrays.


In [ ]:
# Array 1
print("Array1")
print("Mean:",np.mean(arr1))
print("Median:",np.median(arr1))
print("Standard Deviation:",np.std(arr1))

print()

# Array 2
print("Array2")
print("Mean:",np.mean(arr2))
print("Median:",np.median(arr2))
print("Standard Deviation:",np.std(arr2))

Array1
Mean: 4.666666666666667
Median: 5.0
Standard Deviation: 2.560381915956203

Array2
Mean: 4.333333333333333
Median: 4.0
Standard Deviation: 2.309401076758503


5.Find the sum of all elements in Array 2 along the rows and columns.


In [ ]:
# column
print("Column:",np.sum(arr2,axis=0))
# row
print("Row:",np.sum(arr2,axis=1))

Column: [ 6 13 20]
Row: [ 9 12 18]


6.Subtract the mean of each column from Array 2 and Multiply Array 1 by a scalar value.

In [ ]:
# Mean Substraction
print("Mean:")
arr2_mean = np.mean(arr2,axis=0)
print(arr2-arr2_mean)

print()

# Scalar Value Multiplication
print("Scalar Value:")
print(arr1*2)

Mean:
[[-1.         -1.33333333 -1.66666667]
 [ 0.         -0.33333333 -0.66666667]
 [ 1.          1.66666667  2.33333333]]

Scalar Value:
[[ 8 14  2]
 [16  4 12]]


#Array Slicing

7.Extract all elements greater than 5 from Array 2 and Slice Array 2 to get the last two rows and first two columns.


In [ ]:
# Elements greater than 5
print("Greater than 5:",arr2[arr2>5])
print()

# Last two rows
print("Last Two Row:")
print(arr2[-2:])

print()

# First two columns
print("First Two Column:")
print(arr2[:,:2])

Greater than 5: [6 6 9]

Last Two Row:
[[2 4 6]
 [3 6 9]]

First Two Column:
[[1 3]
 [2 4]
 [3 6]]


#Array Sort

8.Sort both arrays and Find the indexes of the maximum value in both arrays.


In [ ]:
# Array 1 sort
np.sort(arr1)
print("Array1 Sort:")
print(arr1)
print()

# Array 2 sort
np.sort(arr2)
print("Array2 Sort:")
print(arr2)
print()

# Max Indexes
print("Array1:",np.argmax(arr1))
print("Array2:",np.argmax(arr2))

Array1 Sort:
[[4 7 1]
 [8 2 6]]

Array2 Sort:
[[1 3 5]
 [2 4 6]
 [3 6 9]]

Array1: 3
Array2: 8
